-- MySQL Script generated by MySQL Workbench
-- 04/27/15 18:32:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `blogdb` ;

-- -----------------------------------------------------
-- Table `blogdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`users` (
  `id` INT PRIMARY KEY NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `passwordHash` VARCHAR(1024) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`posts` (
  `id` INT PRIMARY KEY NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_posts_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`comments` (
  `id` INT PRIMARY KEY NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `body` LONGTEXT NOT NULL,
  `author_name` VARCHAR(256) NOT NULL,
  `author_email` VARCHAR(512) NULL,
  INDEX `fk_comments_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogdb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`tags` (
  `id` INT PRIMARY KEY NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`posts_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`posts_tags` (
  `post_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  INDEX `fk_posts_tags_posts1_idx` (`post_id` ASC),
  INDEX `fk_posts_tags_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_posts_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogdb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `blogdb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
